build:
  stage: build
  script:
    - cd Project_Individual/
    - ./gradlew build
stages: 
  - build
  - test
test: 
  dependencies: "-build -testTask.ignoreFailures = true"
 test:
  stage: test
  script:
    - cd Project_Individual/
    - ./gradlew test