stages:
  - build
  - test
  -Sonarqube
build:
  stage: build
  script:
    - cd Project_Individual/
    - ./gradlew build
test:
  stage: test
  script:
    - cd Project_Individual/
    - ./gradlew test
  dependencies:
    - build
sonarqube
  stage: sonarqube
  script:
    - cd Project_Individual/
    - ./gradlew sonarqube
  dependencies:
    - test